---
call: DeleteBucketAnalyticsConfiguration 
service: S3
tests:
  - expected:
    op: eq
    path: content
  - expected: oneoffpaws 
    op: eq
    path: parameters
    key: Bucket
  - expected: test1333
    op: eq
    path: parameters
    key: id
  - expected: DELETE 
    op: eq
    path: method
  - expected: https://s3.fake_region.amazonaws.com/oneoffpaws?
    path: url
  - expected: id=test1333
    path: url 
  - expected: analytics=
    path: url      
  - expected: /oneoffpaws?
    path: uri
  - expected: id=test1333
    path: uri
  - expected: analytics=
    path: uri

